<?php

namespace Sadeem\Core\Module\Http\Controllers;

use Illuminate\Contracts\Container\BindingResolutionException;
use InvalidArgumentException;
use Sadeem\Core\Module\Contracts\UseCases\UseCaseContract;
use Sadeem\Core\Module\DTOs\DTO;
use Sadeem\Core\Module\Enums\Responders\ResponderType;
use Sadeem\Core\Module\Factories\ResponderFactory;
use Sadeem\Core\Module\Factories\UseCaseFactory;
use Sadeem\Core\Module\Http\Responders\Options\InertiaResponderOptions;
use Sadeem\Core\Module\Http\Responders\Options\RedirectBackResponderOptions;
use Sadeem\Core\Module\Http\Responders\Options\RedirectToRouteResponderOptions;
use Sadeem\Core\Module\Http\Responders\Responder;

/**
 * @property $useCaseClass
 */
abstract class Controller
{
    /**
     * UseCaseFactory instance.
     *
     * @var UseCaseFactory
     */
    protected UsecaseFactory $useCaseFactory;

    /**
     * ResponderFactory instance.
     *
     * @var ResponderFactory
     */
    protected ResponderFactory $responderFactory;

    /**
     * BaseController constructor.
     *
     * @param UsecaseFactory $useCaseFactory
     *   Injected factory used to dynamically create usecases.
     * @param ResponderFactory $responderFactory
     *   Injected factory used to dynamically create responders based on the request type.
     */
    public function __construct(
        UsecaseFactory   $useCaseFactory,
        ResponderFactory $responderFactory
    )
    {
        $this->useCaseFactory = $useCaseFactory;
        $this->responderFactory = $responderFactory;
    }

    /**
     * Resolve and instantiate a use case using the registered factory.
     *
     * @template T of UseCaseContract
     * @param class-string<T> $useCaseClass
     * @return T
     *
     * @throws InvalidArgumentException
     */
    protected function useCase(string $useCaseClass)
    {
        try {
            $instance = $this->useCaseFactory->make($useCaseClass);

            if (!is_object($instance)) {
                throw new InvalidArgumentException("UseCaseFactory must return an object. Got: " . gettype($instance));
            }

            if (!method_exists($instance, 'handle')) {
                throw new InvalidArgumentException("UseCase [$useCaseClass] does not implement handle().");
            }

            return $instance;

        } catch (BindingResolutionException $e) {
            throw new InvalidArgumentException("Unable to resolve UseCase [$useCaseClass] : " . $e->getMessage());
        }
    }


    /**
     * Helper to create responder based on current request using the injected factory.
     *
     * @return Responder
     */
    protected function responder(ResponderType $type = ResponderType::REDIRECT_BACK)
    {
        return $this->responderFactory->make($type);
    }

    /**
     * Execute a UseCase and respond using a specified Responder type.
     *
     * This method centralizes the flow of:
     *   1. Creating a UseCase instance dynamically using the UsecaseFactory.
     *   2. Executing the business logic with the provided data.
     *   3. Creating the Responder instance explicitly using a ResponderType.
     *   4. Wrapping the BaseResponse into the appropriate Options DTO for the Responder.
     *   5. Returning the final response.
     *
     * @param string $serviceClass
     *   Fully qualified class name of the UseCase to execute.
     *   Must implement a `handle (?DTO $data)` method.
     *
     * @param ?DTO $data
     *   The validated data to pass to the UseCase's handle() method.
     *
     * @param ResponderType $responderType
     *   The type of Responder to use for the response (REDIRECT, INERTIA, JSON).
     *
     * @param string|null $component
     *   Optional Inertia component name (only used if $responderType is INERTIA).
     *
     * @return mixed
     *   Returns the response generated by the Responder.
     */
    protected function execute(
        string        $serviceClass,
        ?DTO          $data,
        ResponderType $responderType = ResponderType::REDIRECT_BACK,
        ?string       $component = null,
        ?string       $route = null,
        ?array        $parameters = null,
        array         $extra = []
    )
    {
        // Create the UseCase instance dynamically
        $useCase = $this->usecase($serviceClass);

        // Execute business logic
        $response = $useCase->handle($data);

        // Create the Responder instance explicitly via ResponderType
        $responder = $this->responder($responderType);

        // Wrap Response into proper Options DTO based on a Responder type
        $options = match ($responderType) {
            ResponderType::REDIRECT_BACK => new RedirectBackResponderOptions(
                response: $response
            ),
            ResponderType::REDIRECT_TO_ROUTE => new RedirectToRouteResponderOptions(
                response: $response,
                routeName: $route,
                parameters: $parameters ?? []
            ),
            ResponderType::INERTIA => new InertiaResponderOptions(
                response: $response,
                component: $component ?? 'Dashboard/Index',
                extra: array_merge(
                    [
                        'data' => is_array($response->data)
                            ? array_map(fn($r) => $r->resolve(), $response->data)
                            : $response->data?->resolve() ?? [],
                    ],
                    $extra
                )
            ),
            default => throw new InvalidArgumentException('Unsupported Responder type')
        };

        // Return the response from the Responder
        return $responder->respond($options);
    }
}
